title: M. Abbas Ansari
# logo: /assets/img/headshot_circle.png
#description: text below image

description: Computational Neuroscience Master's Student, </br>University of Tübingen 
github_username: m-abbas-ansari
# email: mohd.abbas.ansari.2001@gmail.com
twitter_username: King_of_Haskul
theme: jekyll-theme-minimal
logo: assets/img/abbas-blue.png

sidebar:
  - name: Email
    icon: fa-regular fa-envelope
    link: mohammed-abbas.ansari@student.uni-tuebingen.de
  # - name: CV
  #   icon: fa-regular fa-file-pdf
  #   link: /assets/docs/cv.pdf
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/m-abbas-ansari
  - name: LinkedIn
    icon: fa-brands fa-linkedin-in
    link: https://www.linkedin.com/in/abbas-ansari-2001/
  - name: Google Scholar
    icon: fa-brands fa-google-scholar
    link: https://scholar.google.com/citations?user=vOIa3kwAAAAJ&hl=en
  - name: X
    icon: fa-brands fa-x-twitter
    link: https://twitter.com/King_of_Haskul


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge